name: Email Step Action

on:
  push:
    branches:
      - main  # or the default branch of your repo

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 23f3001654@ds.study.iitm.ac.in
        run: echo "Hello, world!"
